
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `SCIM_ATTRIBUTE`;
DROP TABLE IF EXISTS `SCIM_USER_ATTRIBUTE`;
DROP TABLE IF EXISTS `SCIM_GROUP`;
DROP TABLE IF EXISTS `SCIM_USER`;
DROP TABLE IF EXISTS `SCIM_ORG`;
DROP TABLE IF EXISTS `SCIM_JOB`;
DROP TABLE IF EXISTS `SCIM_POS`;
DROP TABLE IF EXISTS `SCIM_POLICY`;
DROP TABLE IF EXISTS `SCIM_POLICY_ATTRIBUTE`;
DROP TABLE IF EXISTS `SCIM_POLICY_RESOURCE`;
DROP TABLE IF EXISTS `SCIM_CONSUMER`;
DROP TABLE IF EXISTS `SCIM_PROVIDER`;
DROP TABLE IF EXISTS `SCIM_RESOURCE`;
DROP TABLE IF EXISTS `SCIM_SYSTEM`;
DROP TABLE IF EXISTS `SCIM_SYSTEM_RESOURCE`;

SET FOREIGN_KEY_CHECKS=1;


SELECT * FROM SCIM_GROUP;
SELECT * FROM SCIM_ORG;
SELECT * FROM SCIM_USER;
SELECT * FROM SCIM_USER_ATTRIBUTE;
SELECT * FROM SCIM_ATTRIBUTE;

DELETE FROM SCIM_GROUP WHERE ID='org1'
DELETE FROM SCIM_GROUP WHERE ID='pos1'
DELETE FROM SCIM_ORG WHERE ID='org1'
DELETE FROM SCIM_USER WHERE ID='11111'
DELETE FROM SCIM_ATTRIBUTE WHERE ID='org1pos1job1'
DELETE FROM SCIM_USER_ATTRIBUTE WHERE USER_ID='11111'