package com.raonsecure.sso;
// Generated 2019. 8. 26 ���� 8:55:47 by Hibernate Tools 5.4.3.Final

/**
 * Wa3OrgUser generated by hbm2java
 */
public class Wa3OrgUser implements java.io.Serializable {

	private Wa3OrgUserId id;
	private long validFrom;
	private long validTo;

	public Wa3OrgUser() {
	}

	public Wa3OrgUser(Wa3OrgUserId id, long validFrom, long validTo) {
		this.id = id;
		this.validFrom = validFrom;
		this.validTo = validTo;
	}

	public Wa3OrgUserId getId() {
		return this.id;
	}

	public void setId(Wa3OrgUserId id) {
		this.id = id;
	}

	public long getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(long validFrom) {
		this.validFrom = validFrom;
	}

	public long getValidTo() {
		return this.validTo;
	}

	public void setValidTo(long validTo) {
		this.validTo = validTo;
	}

}
