package com.raonsecure.sso;
// Generated 2019. 8. 26 ���� 8:55:47 by Hibernate Tools 5.4.3.Final

import java.math.BigInteger;
import java.sql.Clob;

/**
 * Wa3UserId generated by hbm2java
 */
public class Wa3UserId implements java.io.Serializable {

	private String id;
	private String name;
	private String rrn;
	private String email;
	private String creator;
	private String modifier;
	private String info;
	private String divId;
	private String orgId;
	private String pathId;
	private String pwd1;
	private String pwd2;
	private long pwdMustChange;
	private BigInteger pwdChangeTime;
	private long pwdRetryCount;
	private BigInteger pwdRetryTime;
	private Clob accountProfile;
	private long accessAllow;
	private long disabled;
	private String disabledReason;
	private long locked;
	private BigInteger loginPolicyId;
	private BigInteger validFrom;
	private BigInteger validTo;
	private BigInteger lastLogonTime;
	private String lastLogonIp;
	private String orgDelayInfo;
	private BigInteger createTime;
	private BigInteger modifyTime;

	public Wa3UserId() {
	}

	public Wa3UserId(String id, String name, String divId, String orgId, String pathId, long pwdMustChange,
			long pwdRetryCount, BigInteger pwdRetryTime, long accessAllow, long disabled, long locked,
			BigInteger validFrom, BigInteger validTo, BigInteger lastLogonTime) {
		this.id = id;
		this.name = name;
		this.divId = divId;
		this.orgId = orgId;
		this.pathId = pathId;
		this.pwdMustChange = pwdMustChange;
		this.pwdRetryCount = pwdRetryCount;
		this.pwdRetryTime = pwdRetryTime;
		this.accessAllow = accessAllow;
		this.disabled = disabled;
		this.locked = locked;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.lastLogonTime = lastLogonTime;
	}

	public Wa3UserId(String id, String name, String rrn, String email, String creator, String modifier, String info,
			String divId, String orgId, String pathId, String pwd1, String pwd2, long pwdMustChange,
			BigInteger pwdChangeTime, long pwdRetryCount, BigInteger pwdRetryTime, Clob accountProfile,
			long accessAllow, long disabled, String disabledReason, long locked, BigInteger loginPolicyId,
			BigInteger validFrom, BigInteger validTo, BigInteger lastLogonTime, String lastLogonIp, String orgDelayInfo,
			BigInteger createTime, BigInteger modifyTime) {
		this.id = id;
		this.name = name;
		this.rrn = rrn;
		this.email = email;
		this.creator = creator;
		this.modifier = modifier;
		this.info = info;
		this.divId = divId;
		this.orgId = orgId;
		this.pathId = pathId;
		this.pwd1 = pwd1;
		this.pwd2 = pwd2;
		this.pwdMustChange = pwdMustChange;
		this.pwdChangeTime = pwdChangeTime;
		this.pwdRetryCount = pwdRetryCount;
		this.pwdRetryTime = pwdRetryTime;
		this.accountProfile = accountProfile;
		this.accessAllow = accessAllow;
		this.disabled = disabled;
		this.disabledReason = disabledReason;
		this.locked = locked;
		this.loginPolicyId = loginPolicyId;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.lastLogonTime = lastLogonTime;
		this.lastLogonIp = lastLogonIp;
		this.orgDelayInfo = orgDelayInfo;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRrn() {
		return this.rrn;
	}

	public void setRrn(String rrn) {
		this.rrn = rrn;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getDivId() {
		return this.divId;
	}

	public void setDivId(String divId) {
		this.divId = divId;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getPathId() {
		return this.pathId;
	}

	public void setPathId(String pathId) {
		this.pathId = pathId;
	}

	public String getPwd1() {
		return this.pwd1;
	}

	public void setPwd1(String pwd1) {
		this.pwd1 = pwd1;
	}

	public String getPwd2() {
		return this.pwd2;
	}

	public void setPwd2(String pwd2) {
		this.pwd2 = pwd2;
	}

	public long getPwdMustChange() {
		return this.pwdMustChange;
	}

	public void setPwdMustChange(long pwdMustChange) {
		this.pwdMustChange = pwdMustChange;
	}

	public BigInteger getPwdChangeTime() {
		return this.pwdChangeTime;
	}

	public void setPwdChangeTime(BigInteger pwdChangeTime) {
		this.pwdChangeTime = pwdChangeTime;
	}

	public long getPwdRetryCount() {
		return this.pwdRetryCount;
	}

	public void setPwdRetryCount(long pwdRetryCount) {
		this.pwdRetryCount = pwdRetryCount;
	}

	public BigInteger getPwdRetryTime() {
		return this.pwdRetryTime;
	}

	public void setPwdRetryTime(BigInteger pwdRetryTime) {
		this.pwdRetryTime = pwdRetryTime;
	}

	public Clob getAccountProfile() {
		return this.accountProfile;
	}

	public void setAccountProfile(Clob accountProfile) {
		this.accountProfile = accountProfile;
	}

	public long getAccessAllow() {
		return this.accessAllow;
	}

	public void setAccessAllow(long accessAllow) {
		this.accessAllow = accessAllow;
	}

	public long getDisabled() {
		return this.disabled;
	}

	public void setDisabled(long disabled) {
		this.disabled = disabled;
	}

	public String getDisabledReason() {
		return this.disabledReason;
	}

	public void setDisabledReason(String disabledReason) {
		this.disabledReason = disabledReason;
	}

	public long getLocked() {
		return this.locked;
	}

	public void setLocked(long locked) {
		this.locked = locked;
	}

	public BigInteger getLoginPolicyId() {
		return this.loginPolicyId;
	}

	public void setLoginPolicyId(BigInteger loginPolicyId) {
		this.loginPolicyId = loginPolicyId;
	}

	public BigInteger getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(BigInteger validFrom) {
		this.validFrom = validFrom;
	}

	public BigInteger getValidTo() {
		return this.validTo;
	}

	public void setValidTo(BigInteger validTo) {
		this.validTo = validTo;
	}

	public BigInteger getLastLogonTime() {
		return this.lastLogonTime;
	}

	public void setLastLogonTime(BigInteger lastLogonTime) {
		this.lastLogonTime = lastLogonTime;
	}

	public String getLastLogonIp() {
		return this.lastLogonIp;
	}

	public void setLastLogonIp(String lastLogonIp) {
		this.lastLogonIp = lastLogonIp;
	}

	public String getOrgDelayInfo() {
		return this.orgDelayInfo;
	}

	public void setOrgDelayInfo(String orgDelayInfo) {
		this.orgDelayInfo = orgDelayInfo;
	}

	public BigInteger getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(BigInteger createTime) {
		this.createTime = createTime;
	}

	public BigInteger getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(BigInteger modifyTime) {
		this.modifyTime = modifyTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Wa3UserId))
			return false;
		Wa3UserId castOther = (Wa3UserId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getRrn() == castOther.getRrn()) || (this.getRrn() != null && castOther.getRrn() != null
						&& this.getRrn().equals(castOther.getRrn())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getCreator() == castOther.getCreator()) || (this.getCreator() != null
						&& castOther.getCreator() != null && this.getCreator().equals(castOther.getCreator())))
				&& ((this.getModifier() == castOther.getModifier()) || (this.getModifier() != null
						&& castOther.getModifier() != null && this.getModifier().equals(castOther.getModifier())))
				&& ((this.getInfo() == castOther.getInfo()) || (this.getInfo() != null && castOther.getInfo() != null
						&& this.getInfo().equals(castOther.getInfo())))
				&& ((this.getDivId() == castOther.getDivId()) || (this.getDivId() != null
						&& castOther.getDivId() != null && this.getDivId().equals(castOther.getDivId())))
				&& ((this.getOrgId() == castOther.getOrgId()) || (this.getOrgId() != null
						&& castOther.getOrgId() != null && this.getOrgId().equals(castOther.getOrgId())))
				&& ((this.getPathId() == castOther.getPathId()) || (this.getPathId() != null
						&& castOther.getPathId() != null && this.getPathId().equals(castOther.getPathId())))
				&& ((this.getPwd1() == castOther.getPwd1()) || (this.getPwd1() != null && castOther.getPwd1() != null
						&& this.getPwd1().equals(castOther.getPwd1())))
				&& ((this.getPwd2() == castOther.getPwd2()) || (this.getPwd2() != null && castOther.getPwd2() != null
						&& this.getPwd2().equals(castOther.getPwd2())))
				&& (this.getPwdMustChange() == castOther.getPwdMustChange())
				&& ((this.getPwdChangeTime() == castOther.getPwdChangeTime())
						|| (this.getPwdChangeTime() != null && castOther.getPwdChangeTime() != null
								&& this.getPwdChangeTime().equals(castOther.getPwdChangeTime())))
				&& (this.getPwdRetryCount() == castOther.getPwdRetryCount())
				&& ((this.getPwdRetryTime() == castOther.getPwdRetryTime())
						|| (this.getPwdRetryTime() != null && castOther.getPwdRetryTime() != null
								&& this.getPwdRetryTime().equals(castOther.getPwdRetryTime())))
				&& ((this.getAccountProfile() == castOther.getAccountProfile())
						|| (this.getAccountProfile() != null && castOther.getAccountProfile() != null
								&& this.getAccountProfile().equals(castOther.getAccountProfile())))
				&& (this.getAccessAllow() == castOther.getAccessAllow())
				&& (this.getDisabled() == castOther.getDisabled())
				&& ((this.getDisabledReason() == castOther.getDisabledReason())
						|| (this.getDisabledReason() != null && castOther.getDisabledReason() != null
								&& this.getDisabledReason().equals(castOther.getDisabledReason())))
				&& (this.getLocked() == castOther.getLocked())
				&& ((this.getLoginPolicyId() == castOther.getLoginPolicyId())
						|| (this.getLoginPolicyId() != null && castOther.getLoginPolicyId() != null
								&& this.getLoginPolicyId().equals(castOther.getLoginPolicyId())))
				&& ((this.getValidFrom() == castOther.getValidFrom()) || (this.getValidFrom() != null
						&& castOther.getValidFrom() != null && this.getValidFrom().equals(castOther.getValidFrom())))
				&& ((this.getValidTo() == castOther.getValidTo()) || (this.getValidTo() != null
						&& castOther.getValidTo() != null && this.getValidTo().equals(castOther.getValidTo())))
				&& ((this.getLastLogonTime() == castOther.getLastLogonTime())
						|| (this.getLastLogonTime() != null && castOther.getLastLogonTime() != null
								&& this.getLastLogonTime().equals(castOther.getLastLogonTime())))
				&& ((this.getLastLogonIp() == castOther.getLastLogonIp())
						|| (this.getLastLogonIp() != null && castOther.getLastLogonIp() != null
								&& this.getLastLogonIp().equals(castOther.getLastLogonIp())))
				&& ((this.getOrgDelayInfo() == castOther.getOrgDelayInfo())
						|| (this.getOrgDelayInfo() != null && castOther.getOrgDelayInfo() != null
								&& this.getOrgDelayInfo().equals(castOther.getOrgDelayInfo())))
				&& ((this.getCreateTime() == castOther.getCreateTime()) || (this.getCreateTime() != null
						&& castOther.getCreateTime() != null && this.getCreateTime().equals(castOther.getCreateTime())))
				&& ((this.getModifyTime() == castOther.getModifyTime())
						|| (this.getModifyTime() != null && castOther.getModifyTime() != null
								&& this.getModifyTime().equals(castOther.getModifyTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getRrn() == null ? 0 : this.getRrn().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getCreator() == null ? 0 : this.getCreator().hashCode());
		result = 37 * result + (getModifier() == null ? 0 : this.getModifier().hashCode());
		result = 37 * result + (getInfo() == null ? 0 : this.getInfo().hashCode());
		result = 37 * result + (getDivId() == null ? 0 : this.getDivId().hashCode());
		result = 37 * result + (getOrgId() == null ? 0 : this.getOrgId().hashCode());
		result = 37 * result + (getPathId() == null ? 0 : this.getPathId().hashCode());
		result = 37 * result + (getPwd1() == null ? 0 : this.getPwd1().hashCode());
		result = 37 * result + (getPwd2() == null ? 0 : this.getPwd2().hashCode());
		result = 37 * result + (int) this.getPwdMustChange();
		result = 37 * result + (getPwdChangeTime() == null ? 0 : this.getPwdChangeTime().hashCode());
		result = 37 * result + (int) this.getPwdRetryCount();
		result = 37 * result + (getPwdRetryTime() == null ? 0 : this.getPwdRetryTime().hashCode());
		result = 37 * result + (getAccountProfile() == null ? 0 : this.getAccountProfile().hashCode());
		result = 37 * result + (int) this.getAccessAllow();
		result = 37 * result + (int) this.getDisabled();
		result = 37 * result + (getDisabledReason() == null ? 0 : this.getDisabledReason().hashCode());
		result = 37 * result + (int) this.getLocked();
		result = 37 * result + (getLoginPolicyId() == null ? 0 : this.getLoginPolicyId().hashCode());
		result = 37 * result + (getValidFrom() == null ? 0 : this.getValidFrom().hashCode());
		result = 37 * result + (getValidTo() == null ? 0 : this.getValidTo().hashCode());
		result = 37 * result + (getLastLogonTime() == null ? 0 : this.getLastLogonTime().hashCode());
		result = 37 * result + (getLastLogonIp() == null ? 0 : this.getLastLogonIp().hashCode());
		result = 37 * result + (getOrgDelayInfo() == null ? 0 : this.getOrgDelayInfo().hashCode());
		result = 37 * result + (getCreateTime() == null ? 0 : this.getCreateTime().hashCode());
		result = 37 * result + (getModifyTime() == null ? 0 : this.getModifyTime().hashCode());
		return result;
	}

}
