package com.raonsecure.sso;
// Generated 2019. 8. 26 ���� 8:55:47 by Hibernate Tools 5.4.3.Final

/**
 * Wa3User generated by hbm2java
 */
public class Wa3User implements java.io.Serializable {

	private Wa3UserId id;

	public Wa3User() {
	}

	public Wa3User(Wa3UserId id) {
		this.id = id;
	}

	public Wa3UserId getId() {
		return this.id;
	}

	public void setId(Wa3UserId id) {
		this.id = id;
	}

}
